name: AQI Forecast CI/CD Pipeline

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour (UTC)
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-train-predict:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.10"
      AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      AQI_FORECAST_API_KEY: ${{ secrets.AQI_FORECAST_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify environment
        run: |
          echo "Python version:"
          python --version
          echo "Installed hopsworks version:"
          pip list | grep hopsworks

      # Step 1: Backfill latest data
      - name: Backfill AQI & weather data
        run: python features/features/backfill.py


      # Step 2: Train model
      - name: Train Random Forest model
        run: python trainings/train_sklearn.py

      # Step 3: Predict using latest model
      - name: Generate predictions
        run: python trainings/predict.py

      # Step 4: Commit predictions
      - name: Commit prediction results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/predictions/latest_predictions.csv || true
          git commit -m "Auto-update: latest predictions [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
