name: AQI Forecast CI/CD Pipeline

on:
  schedule:
    - cron: "0 * * * *"   # Every hour (UTC)
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-train-predict:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.10"
      AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      AQI_FORECAST_API_KEY: ${{ secrets.AQI_FORECAST_API_KEY }}

    steps:
      # ------------------------
      # 1. Setup environment
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify environment
        run: |
          echo "Python version:"
          python --version
          echo "Installed hopsworks version:"
          pip list | grep hopsworks || echo "Hopsworks not found!"

      # ------------------------
      # 2. Data Backfill
      # ------------------------
      - name: Backfill AQI & Weather Data
        run: python features/features/backfill.py

      # ------------------------
      # 3. Exploratory Data Analysis (EDA)
      # ------------------------
      - name: Run EDA on latest features
        env:
          AQI_FORECAST_API_KEY: ${{ secrets.AQI_FORECAST_API_KEY }}
        run: python eda.py

      - name: Commit updated EDA outputs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add eda_outputs/* || true
          git commit -m "Auto-update: EDA outputs [skip ci]" || echo "No EDA changes to commit"
          git push || echo "No EDA changes to push"

      # ------------------------
      # 4. Train and Predict
      # ------------------------
      - name: Train Random Forest model
        run: python trainings/train_sklearn.py

      - name: Generate Predictions
        run: python trainings/predict.py

      - name: Commit latest predictions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/predictions/latest_predictions.csv || true
          git commit -m "Auto-update: Latest predictions [skip ci]" || echo "No prediction changes to commit"
          git push || echo "No prediction changes to push"

      # ------------------------
      # 5. Sync EDA results to Dashboard
      # ------------------------
      - name: Sync EDA outputs to dashboard
        run: |
          mkdir -p dashboard/eda_outputs
          cp -r eda_outputs/* dashboard/eda_outputs/ || echo "No EDA outputs found"
          git add dashboard/eda_outputs/* || true
          git commit -m "🪄 Sync: EDA outputs to dashboard [skip ci]" || echo "No dashboard changes"
          git push || echo "No dashboard changes to push"
