name: Run EDA from Hopsworks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # optional: runs daily at 6 AM UTC

jobs:
  eda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install hopsworks pandas seaborn matplotlib

      - name: Run EDA
        env:
          aqi_forecast_api_key: ${{ secrets.AQI_FORECAST_API_KEY }}
        run: python eda.py

      - name: Commit and push EDA results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add eda_outputs/*
          git commit -m "📊 Updated EDA results from Hopsworks"
          git push
